config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end

  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kitten }
    end
  end

  def create
    @kitten = Kitten.create(kitten_params)
    redirect_to root_url
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:sucess] = "Kitten updated"
      redirect_to @kitten
    else
      flash.now[:warning] = "The kitten was not updated"
      render 'edit'
    end
  end

  def destroy
    if Kitten.find(params[:id]).destroy
      flash[:sucess] = "Kitten deleted"
      redirect_to root_url
    else
      flash.now[:warning] = "The kitten was not deleted"
    end
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<li>
  <%= link_to kitten.id, kitten %>
  Name: <%= kitten.name %>
  Age: <%= kitten.age %>
  Cuteness: <%= kitten.cuteness %>
  Softness: <%= kitten.softness %>
  <%= link_to "edit", kitten, method: :edit %>
  <%= link_to "delete", @kitten, method: :delete,
                        data: {confirm: "Are you sure?"}%>
</li>

app/views/kittens/edit.html.erb
<% provide(:title, 'Edit Kitten')%>
<% provide(:button, 'Edit Kitten') %>
<%= render '/layouts/kitten_form' %>

app/views/kittens/index.html.erb
<ul>
  <%= render @kittens %>
</ul>

app/views/kittens/new.html.erb
<% provide(:title, 'New Kitten') %>
<% provide(:button, 'Create Kitten') %>
<%= render '/layouts/kitten_form' %>

app/views/kittens/show.html.erb
<ul>
  <li>Kitten <%= @kitten.id %></li>
  <li>Name: <%= @kitten.name %></li>
  <li>Age: <%= @kitten.age %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
  <li><%= link_to "edit", edit_kitten_url(@kitten) %></li>
  <li><%= link_to "delete", @kitten, method: :delete,
                                  data: {confirm: "Are you sure?"}%></li>
</ul>

app/views/layouts/_kitten_form.html.erb
<h1><%= :title %></h1>
<div id="<%= :title %>_form">
  <%= form_for @kitten do |f| %>
    <%= f.label  :name %>
    <%= f.text_field   :name %>
    <%= f.label  :age %>
    <%= f.text_field   :age %>
    <%= f.label  :cuteness %>
    <%= f.text_field   :cuteness %>
    <%= f.label  :softness %>
    <%= f.text_field   :softness %>
    <%= f.submit :button %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKitten</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>